### ISSUE TITLE
Use rational numbers for semantic sound duration

### ISSUE THREAD

**Issue by alice-i-cecile** [tesselode/kira#14]
This is a more natural representation than an f64 (e.g. a 1/3 note in 4/4 time has a 1/12 semantic duration), and does not accumulate error over time in subtle or frustrating ways.

**Comment by tesselode** [comment]
how do i go about doing that?

**Comment by alice-i-cecile** [comment]
The [num-rational crate](https://crates.io/crates/num-rational) has been super easy to use for me in the past :) Might make sense as an opt-in feature though; many of your downstream use cases won't care about this functionality and would prefer to avoid the extra dependency.

**Comment by tesselode** [comment]
@alice-i-cecile given that Kira no longer has semantic durations, but it does have clocks, do you still see any utility for rational numbers? I don't think floating point error will be a problem for clocks, since the error is accumulated with each tick.

**Comment by alice-i-cecile** [comment]
Yep should be fine.
