### ISSUE TITLE
Sequencer in new API

### ISSUE THREAD

**Issue by Bluskript** [tesselode/kira#16]
In the new kira API, sequencers don't seem to exist. It would be useful to be able to define sequencers of some kind in order to define simple patterns, probably using clock ticks instead of beats (writing a metronome in the new API requires creating many clock instances).

**Comment by tesselode** [comment]
Hi, exciting to see someone is noticing the new changes before I've officially announced them!

You don't need multiple clocks to create a metronome. You can use `clock_handle.time().ticks % beats_per_measure` to get the current beat.

**Comment by Geoxor** [comment]
I see, because we are working on a DAW in Rust and Vue and we wanted to implement the new version of this library since we saw that it now has streaming support but we couldn't figure out how to do the sequencing, thank you :0!!
