### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by Roms1383** [tesselode/kira#18]
Hello and high five for this crate, it indeed looks great!

I'm trying it today for the first time and followed the instructions on docs.rs and also from the book (very good initiative).
TBH my audio knowledge is inexistent, but luckily by following your instructions it doesn't look that difficult.

Just opening this issue here because there's some inconsistencies in the examples, e.g.
- with `load` / `load_sound` where the docs points out to [kira-loaders](https://crates.io/crates/kira-loaders), but indeed doesn't look necessary anymore (`AudioManager`'s `load_sound` seems the way to go).
- there's something regarding cpal pointing at [kira-cpal](https://crates.io/crates/kira-cpal) but I personally didn't need it to play a sound (on MacOS M1).
- one piece of advice I would have given to newcomers, is that you need to have your program running for as long as the loading of the file + the sound duration, which can easily be achieved by e.g. using tokio sleep for as long as it lasts.
- I'm especially interested in updates to the `mixer` section, which is the one I'm the most interested into.

Thanks :)

**Comment by Roms1383** [comment]
To add some more context, what confuses me the most is that I created some manager e.g.:
```rust
#[tokio::main]
async fn main() {
    let now = Instant::now();
    let folder = std::env::var("CARGO_MANIFEST_DIR").expect("manifest dir");
    let file = std::path::Path::new(&folder).join("welcome.mp3");
    let mut audio_manager =
        AudioManager::new(AudioManagerSettings::default()).expect("audio manager");
    let mut sound_handle = audio_manager
        .load_sound(file, SoundSettings::default())
        .expect("sound handle");
    sound_handle
        .play(InstanceSettings::default())
        .expect("play sound");
    let duration = sound_handle.duration() as u64;
    let latency = now.elapsed().as_secs_f64() as u64 + 1u64; // add some offset otherwise too short
    sleep(Duration::from_secs(duration + latency)).await; // allows for playing the sound till its end
}
```
So far I've seen that I can add an Effect (e.g. cutoff) to the MainTrackHandle, but couldn't find how to get a reference to it.
I've looked into adding a send track or a sub track, but so far I'm still confuse on how to use kira properly.

**Comment by Roms1383** [comment]
Well my bad, I've actually finally found out [main_track](https://docs.rs/kira/latest/kira/manager/struct.AudioManager.html#method.main_track) and the rest, so I guess it works even if maybe not the best way to do it:
```rust
let effect = Filter::new(FilterSettings::new().cutoff(1000.0));
audio_manager
    .main_track()
    .add_effect(
        effect,
        EffectSettings {
            id: None,
            enabled: true,
            mix: 0.9.into(),
        },
    )
    .expect("effect");
```

**Comment by tesselode** [comment]
Hi! The book is for kira v0.6.0, which is in beta. You can see the corresponding docs page for that version [here](https://docs.rs/kira/0.6.0-beta.0/kira/index.html).

**Comment by Roms1383** [comment]
Thanks @tesselode your crate is really awesome, can't wait to see how it evolves. The simple fact that somebody like me who has literally zero knowledge about sound and still I'm able to produce something with a satisfying result is just incredible haha I'm having a blast !
