### ISSUE TITLE
`kira-loaders` does not support loading files from memory

### ISSUE THREAD

**Issue by simast** [tesselode/kira#19]
The old (0.5) implementation had support for loading files directly from memory (`from_ogg_reader` etc) instead of file paths. Could we have the same feature in the new version as well?

This would support things like loading sound files from archives, virtual filesystems or network.

**Comment by tesselode** [comment]
Symphonia can only load audio from `File`s or `Cursor`s - would `load_from_cursor`/`stream_from_cursor` functions be useful?

**Comment by simast** [comment]
At least for my case `Cursor`'s would work just fine.

**Comment by tesselode** [comment]
Added in v0.6.0-beta-2.
