### ISSUE TITLE
Expose loaders and cpal backend using features?

### ISSUE THREAD

**Issue by simast** [tesselode/kira#20]
This is really more like a question here. But I found having separate crates I need to have dependencies on core functionality a bit weird. Would it not be better instead of requiring users to have separate dependencies in their Cargo.toml - have the `kira-cpal` and `kira-loaders` exposed as features instead? Internally you still have multiple crates, they can still be disabled with `default-features = false`, custom backend/loader still can be implemented by user, etc.

At least from my experience in Rust this seems to be a more common approach in libraries, but maybe there is a good reason it is the way it is?

**Comment by tesselode** [comment]
`kira-cpal` and `kira-loaders` would not work on wasm, so I think if I exposed it as a feature, I'd also have to make it available only on desktop targets? That seems a little awkward to me.

**Comment by tesselode** [comment]
cpal and loaders are now exposed as features in v0.6.0 beta 6.
