### ISSUE TITLE
Upgrade to Symphonia v0.5

### ISSUE THREAD

**Issue by Shnatsel** [tesselode/kira#21]
Symphonia v0.5 has recently shipped with much improved support for MP3, as well as improvements for pretty much the entire rest of the codecs it supports. I see `kira-loaders` currently uses v0.4; it would be nice to upgrade to v0.5 to get those improvements.

v0.5 is not semver compatible with v0.4.x, so Kira users will not get this upgrade simply by running `cargo update`; this requires an explicit version bump in your `Cargo.toml`.

**Comment by tesselode** [comment]
I never responded to this (sorry!), but I will be upgrading to Symphonia v0.5 in the next kira-loaders release.

**Comment by tesselode** [comment]
Updated in ab7fc51.
