### ISSUE TITLE
Glitchy playback on macOS

### ISSUE THREAD

**Issue by fredlb** [tesselode/kira#23]
Hello, I'm using kira to make a simple little podcast player with a terminal interface, and its been really nice to use so far :)
I am however experiencing some subtle but audible glitches when playing MP3 files on macOS (I have not tried any other OS). I've tried several different files and they all seem to have the same problem.
At first I thought it could have been something with the StreamingSound setup that made this happen, but I'm having the same issues using StaticSound.
I can reproduce it locally using the `simple_sound_playback` with one of the files I have (seems any MP3 file would do).

Additionally, I tried playing the same file in the example `symphonia-play` in the Symphonia repo, which did not exhibit the same issue.

Let me know if you want more information, or if I can help out in any way!

**Comment by tesselode** [comment]
By any chance, can you record the output of your program and post it here?

What optimization level are you using?

**Comment by fredlb** [comment]
Here is a recording of the output that contains the glitches https://drive.google.com/file/d/1Lf6XyiKoxU6p2N7qPTrQXa3XRBP0SCqO/view and its a brief recording of this source https://www.podtrac.com/pts/redirect.mp3/traffic.megaphone.fm/ADV7712059188.mp3.

The result seems to be same regardless of optimization levels, tried 0 and 3.

**Comment by tesselode** [comment]
Is [this](https://github.com/fredlb/fred_podplayer_tui) the program in question?

**Comment by tesselode** [comment]
I got your podcast app running on Windows, and I didn't have any audio glitches. I used the [Song Exploder podcast](http://feed.songexploder.net/songexploder).

Are you able to test on another OS?

**Comment by fredlb** [comment]
Alright scratch all this. For some reason the playback is glitched when using Airpods. I should have ofc tried it with something else! Sorry!

**Comment by tesselode** [comment]
Interesting! I think that's still an issue worth investigating, although I don't know anything about airpods and how they differ from other playback devices.

**Comment by fredlb** [comment]
I'll try and see how it behaves with other bluetooth headphones on Linux and Mac this coming week to pinpoint if its just related to Airpods. Anyway, I'll close this issue for now since its not really accurate. Thanks for you time!
