### ISSUE TITLE
StaticSoundHandle is not Clone-able

### ISSUE THREAD

**Issue by nobbele** [tesselode/kira#25]

**Comment by nobbele** [comment]
I misunderstood the use of this, I don't need it to be Clone-able myself but it could still be made Clone-able I think

**Comment by tesselode** [comment]
If cloning a sound handle is a common enough use case, I could wrap the producer in a `Mutex` to make the handle cloneable. For now, you can wrap the sound handle in a `Mutex` yourself if you want shared ownership.
