### ISSUE TITLE
Tween Default

### ISSUE THREAD

**Issue by nobbele** [tesselode/kira#26]
Default for Tween being 10ms linear easing is quite weird, there should at least be some way to create a 0ms tween

**Comment by nobbele** [comment]
Probably doesn't matter though, 10ms is too little

**Comment by tesselode** [comment]
You can create a 0ms tween, but that's actually too fast. There are audible audio artifacts when you change a parameter instantly. 10ms is fast enough to _feel_ instant, but slow enough to avoid those artifacts.

**Comment by nobbele** [comment]
I thought that might be the reason but I am getting some artifacts even with the default tween when panning. I might open a separate issue with more details.
