### ISSUE TITLE
Feature Request: Method to Create StreamingSoundData from Symphonia MediaSource

### ISSUE THREAD

**Issue by The-Minecraft-Scientist** [tesselode/kira#33]
There are some (admittedly rare) cases where making a Cursor out of sound data isn't practical, while implementing Read+Seek and a few helper methods is (my particular use case is[ rewriting the Minecraft sound system](https://github.com/The-Minecraft-Scientist/WIP-Sound-Mod), where I use callbacks to access a Java BufferedInputStream from Rust and implement Read+Seek on it)

**Comment by tesselode** [comment]
I'm not doubting you, but why can't you make a `Cursor` out of the sound data?

**Comment by The-Minecraft-Scientist** [comment]
I'm wrapping a Java InputStream object over FFI and it's a lot simpler to implement Seek+Read on it.

**Comment by vdrn** [comment]
I'd like this too. I pack all my assets into one large file, and this would enable me to stream music directly from that file. 
Creating `Cursor` requires all data to be loaded in memory first.

**Comment by tesselode** [comment]
Added `StaticSoundData::from_media_source` and `StreamingSoundData::from_media_source` in v0.8.1. @The-Minecraft-Scientist @vdrn let me know if you need versions of those functions that take `Box<dyn MediaSource>`.
