### ISSUE TITLE
Feature request: looping behaviour changes during playback

### ISSUE THREAD

**Issue by viluon** [tesselode/kira#34]
Would it be feasible to implement changes to the looping behaviour in `StreamingSoundHandle`/`StaticSoundHandle`?

**Comment by tesselode** [comment]
I don't see why not. There's certainly room for more functionality related to looping. What's your use case?

**Comment by viluon** [comment]
I'm actually building a [soundboard app](https://github.com/viluon/afx) with kira. I tried rodio and using sypmhonia/cpal/libpulse directly, but rodio doesn't support seeking and the low-level libraries are, well, too low-level. kira's API is a breath of fresh air, a high-level, easy-to-use interface that doesn't compromise on features. The static sound functionality lets me visualise the waveform using the same library that I use for streaming playback.
https://user-images.githubusercontent.com/7235381/204112926-93e98e67-3e9c-4bbb-be89-b4468943da80.mp4

**Comment by tesselode** [comment]
[Implemented in Kira v0.8.](https://docs.rs/kira/latest/kira/sound/static_sound/struct.StaticSoundSettings.html#method.loop_region)
