### ISSUE TITLE
Build StaticSoundData from buffer

### ISSUE THREAD

**Issue by dcvz** [tesselode/kira#44]
Hello all,

I’m attempting to use this in a game (more similar to an emulator) where I’m receiving audio data in a u8 buffer. I tried looking around but it seems there’s no real way of creating a sound data object that I can just send off to play. I already know the num of channels and rate.

It could also be this library isn’t meant to be used this way. Any help would be appreciated :)

**Comment by tesselode** [comment]
To be clear, the audio bytes weren't an existing audio file format, like wav or mp3, right?
