### ISSUE TITLE
Rename set_pitch

### ISSUE THREAD

**Issue by NotGate** [tesselode/kira#9]
I believe the `set_pitch` function is incorrectly named. It just changes the playback rate of the music. 

Changing the pitch without affecting playback rate would involve techniques like phase vocoding (as far as I know) or using a library like Rubber Band: https://en.wikipedia.org/wiki/Audio_time_stretching_and_pitch_scaling#Phase_vocoder
https://breakfastquay.com/rubberband/

`set_pitch` should probably be called something like `set_playback_rate`.

**Comment by tesselode** [comment]
i will conduct some market research!

**Comment by tesselode** [comment]
you were right!
